// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2Ih5jnt4dSqjFwyKjoiKbMFQgZGhE7Ko',
    appId: '1:141225553621:web:dda2d152c62640d05b7c5c',
    messagingSenderId: '141225553621',
    projectId: 'iaapp-30b44',
    authDomain: 'iaapp-30b44.firebaseapp.com',
    storageBucket: 'iaapp-30b44.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJCI5ANL_vOz-UlTgx666GNSUunk2i9pY',
    appId: '1:141225553621:android:6479b787287d29bd5b7c5c',
    messagingSenderId: '141225553621',
    projectId: 'iaapp-30b44',
    storageBucket: 'iaapp-30b44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKRAu0mdwjKjj8Zhm6R2XX8a_SiPHx6js',
    appId: '1:141225553621:ios:b90a81938227cc885b7c5c',
    messagingSenderId: '141225553621',
    projectId: 'iaapp-30b44',
    storageBucket: 'iaapp-30b44.appspot.com',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKRAu0mdwjKjj8Zhm6R2XX8a_SiPHx6js',
    appId: '1:141225553621:ios:5e4aa44b45100de65b7c5c',
    messagingSenderId: '141225553621',
    projectId: 'iaapp-30b44',
    storageBucket: 'iaapp-30b44.appspot.com',
    iosBundleId: 'com.example.untitled3.RunnerTests',
  );
}
